### ISSUE TITLE
[BUG] Mouse move Events are picked up in OverviewBar even when no button is pressed

### ISSUE THREAD

**Issue by marsipu** [mne-tools/mne-qt-browser#137] opened 2022-08-03 21:35 UTC
#### Describe the bug
When the mouse moves over the overview-bar, it changes the viewed windows without having pressed any mouse button. Originally it should only allow clicking and dragging of the window in the overview-bar.

#### Steps to reproduce
```python
sample_data_folder = mne.datasets.sample.data_path()
raw_file = os.path.join(sample_data_folder, 'MEG', 'sample',
                        'sample_audvis_raw.fif')
raw = mne.io.read_raw(raw_file)
raw.plot(block=True)
```

#### Expected results
Viewing Window is only changed, when mouse is pressed and dragged in overview-bar.

#### Actual results☺
Viewing Window is changed everytime the mouse is entering the overview-bar.

#### Additional information
This might be due to the recent update of `pyqt` on conda-forge to `5.15.4`.
This part of the code (line 1060) should only be running if a button is pressed, [as Qt-Documentation](https://doc.qt.io/qt-5/qmouseevent.html#details) states.
```python
def mouseMoveEvent(self, event):
    """Customize mouse move events."""
    self._set_range_from_pos(event.pos())
```
`OverviewBar.hasMouseTracking()==False` so I am not sure what the reason is.

My sys_info is:
```
Platform:         Windows-10-10.0.22000-SP0
Python:           3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 06:57:19) [MSC v.1929 64 bit (AMD64)]
Executable:       C:\Users\marti\anaconda3\envs\mnedev\python.exe
CPU:              Intel64 Family 6 Model 158 Stepping 9, GenuineIntel: 8 cores
Memory:           15.9 GB

mne:              1.1.0
numpy:            1.22.4 {blas=NO_ATLAS_INFO, lapack=lapack}
scipy:            1.8.1
matplotlib:       3.5.2 {backend=QtAgg}

sklearn:          1.1.1
numba:            0.55.2
nibabel:          4.0.1
nilearn:          0.9.1
dipy:             1.5.0
cupy:             Not found
pandas:           1.4.3
pyvista:          0.35.1 {OpenGL 4.4.0 - Build 21.20.16.4526 via Intel(R) HD Graphics 630}
pyvistaqt:        0.9.0
ipyvtklink:       0.2.2
vtk:              9.1.0
qtpy:             2.1.0 {PyQt5=5.15.4}
ipympl:           Not found
pyqtgraph:        0.12.4
pooch:            v1.6.0

mne_bids:         0.11.dev0
mne_nirs:         Not found
mne_features:     Not found
mne_qt_browser:   0.4.dev0
mne_connectivity: 0.4dev0
mne_icalabel:     Not found
```

**Comment by hoechenberger** [comment] 2022-08-11 07:55
I'm seeing the same issue on Windows 10. Extremely annoying; I had to turn off the overview bar so this problem wouldn't constantly get in my way.

**Comment by hoechenberger** [comment] 2022-08-11 10:13
Same problem with the channel selection window.

![image](https://user-images.githubusercontent.com/2046265/184112012-3f561801-6065-4d1f-8f3e-cda0a67407f6.png)

This happened by just moving the mouse across the window. No clicking involved. This is on Windows 10.

**Comment by cbrnr** [comment] 2022-08-11 10:29
I cannot reproduce (macOS, PySide6). I suspect that PyQt5/PySide2 could be the culprit, since these are deprecated versions with many bugs that won't be fixed. Can you try if upgrading to PySide6 solves this issue?

**Comment by hoechenberger** [comment] 2022-08-11 10:34
No, I've tried such an upgrade a few months back and it broke my Python env, which I cannot afford to do right now, sorry

**Comment by cbrnr** [comment] 2022-08-11 11:15
I forgot you are using conda, where I guess PySide6 is not available.

**Comment by hoechenberger** [comment] 2022-08-11 11:33
Yes, unfortunately we're stuck with Qt5 there for now :(

**Comment by hoechenberger** [comment] 2022-08-11 16:11
Qt packaging on conda-forge seems to be mostly motivated by Spyder folks. A hack could be to sneak code into Spyder that ends up requiring Qt6 😅😅😅

**Comment by marsipu** [comment] 2022-08-12 14:29
I installed PyQt6 and PySide6 in a conda-environment with pip and both versions seem to resolve the issue on Windows 11.

But I also found something peculiar:
In a clean conda-environment, just installing `mne-qt-browser` + `PyQt5==5.15.7` either with `pip` or `conda-forge` doesn't have this bug too. Could it be that some package coming with the full mne-installation via conda causes this?

**Comment by marsipu** [comment] 2022-08-12 14:59
When installing `mne-base` and `pyqt` from `conda-forge`, the bug also appears. This narrows it down a bit, right?

**Comment by hoechenberger** [comment] 2022-08-12 15:15
Is the overview bar plotted through Matplotlib or is this a native thing via pyqtgraph?

**Comment by marsipu** [comment] 2022-08-12 15:25
Ok, installing `pyqt` from `conda-forge` seems to be the problem (regardless of what I wrote above). When installed with `pip` there is no problem.
Also installing `pyqt==5.12.3` from `conda-forge` has no problem.

**So the bug only seems to appear when `pyqt>=5.15.4` is installed with `conda`.**

**Comment by marsipu** [comment] 2022-08-12 15:26
> Is the overview bar plotted through Matplotlib or is this a native thing via pyqtgraph?

OverviewBar is just `PyQt`, not including pyqtgraph or other additional packages

**Comment by hoechenberger** [comment] 2022-08-12 15:32
Thanks for tracking this down!!!

Do you think we could procure a MWE somehow?

**Comment by cbrnr** [comment] 2022-08-12 17:19
There's always 5.15.3 and 5.15.2 to try, but I suspect they will have other bugs that might or might not be worse.

**Comment by hoechenberger** [comment] 2022-08-12 17:35
Do we only see this issue on Windows?

**Comment by marsipu** [comment] 2022-08-12 18:02
> There's always 5.15.3 and 5.15.2 to try, but I suspect they will have other bugs that might or might not be worse.

With
```
conda search -c conda-forge pyqt
```
I only got` 5.15.7`,` 5.15.4`, `5.12.3` and so on.
Or is there a trick to get to other versions?

**Comment by cbrnr** [comment] 2022-08-12 18:18
https://anaconda.org/conda-forge/qt/files?version=5.15.3

**Comment by hoechenberger** [comment] 2022-08-12 18:30
> https://anaconda.org/conda-forge/qt/files?version=5.15.3

That's qt, but @marsipu asked about pyqt

**Comment by cbrnr** [comment] 2022-08-12 18:35
Ah, my bad. Weird that they have different versions.

**Closed** 2022-08-27 09:04 UTC
Labels: bug

**Comment by hoechenberger** [comment] 2022-10-07 10:59
FYI, Qt 6 just hit `conda-forge`:
https://github.com/conda-forge/qt-main-feedstock/pull/44

cc @larsoner
